name: Build Linux

on:
  workflow_dispatch:

jobs:
  build-ubuntu:
    strategy:
      matrix:
        architecture: [x86_64, arm64]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka==2.4.10
          pip install PySide6==6.8.0.1

      - name: Build with Nuitka
        run: |
          VERSION=$(python3 -c "from app.common.setting import VERSION; print(VERSION)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          python deploy.py

      - name: Download and extract tools
        run: |
          # Setup variables
          ZIP_URL="https://github.com/zhiyiYo/Fluent-M3U8-Tools/releases/download/v0.1.0/Linux-${{ matrix.architecture }}.zip"
          DEST_DIR="dist/Fluent-M3U8.dist"

          # Download tools
          echo "Downloading package from $ZIP_URL..."
          curl -L "$ZIP_URL" -o "/tmp/package.zip"

          # unzip
          echo "Extracting package..."
          unzip -o "/tmp/package.zip" -d "$DEST_DIR"

          # delete zip
          rm "/tmp/package.zip"

          echo "Download and extraction complete!"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fluent-M3U8-v${{ env.VERSION }}-Linux-${{ matrix.architecture }}
          path: dist/Fluent-M3U8.dist
