name: Build macOS Apple

on:
  workflow_dispatch:

jobs:
  build-macos-14-arm:
    strategy:
      fail-fast: false
      matrix:
        architecture: [arm64]
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          VERSION=$(python3 -c "from app.common.setting import VERSION; print(VERSION)")
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          python deploy.py
          chmod u+x "dist/Fluent-M3U8.app/Contents/MacOS/Fluent-M3U8"
          rm -rf "dist/Fluent-M3U8.build"

      - name: Download and extract tools
        run: |
          # Setup variables
          ZIP_URL="https://github.com/zhiyiYo/Fluent-M3U8-Tools/releases/download/v0.2.0/macOS-${{ matrix.architecture }}.zip"
          DEST_DIR="dist/Fluent-M3U8.app/Contents/MacOS/tools"

          # Download tools
          echo "Downloading package from $ZIP_URL..."
          curl -L "$ZIP_URL" -o "/tmp/package.zip"

          # unzip
          echo "Extracting package..."
          unzip -o "/tmp/package.zip" -d "$DEST_DIR"

          # delete zip
          rm "/tmp/package.zip"

          echo "Download and extraction complete!"

      - name: Create DMG
        run: |
          ln -s /Applications dist/Applications

          attempt=0
          max_attempts=10
          while [ $attempt -lt $max_attempts ]; do
              hdiutil create -srcfolder "dist/" -volname "Fluent-M3U8" -fs HFS+ \
                  -fsargs "-c c=64,a=16,e=16" -format UDZO -size 400m \
                  "Fluent-M3U8-v${{ env.VERSION }}-macOS-${{ matrix.architecture }}.dmg" && break

              attempt=$((attempt + 1))
              echo "Attempt $attempt failed, retrying..."
              sleep 1  # 等待 1 秒后重试
          done

          if [ $attempt -eq $max_attempts ]; then
              echo "Failed to create DMG after $max_attempts attempts"
              exit 1
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Fluent-M3U8-v${{ env.VERSION }}-macOS-${{ matrix.architecture }}
          path: Fluent-M3U8-v${{ env.VERSION }}-macOS-${{ matrix.architecture }}.dmg

